@Echo Off

Set THIS_DIR_PATH=%~dp0
Set LOG_FILE_PATH="%THIS_DIR_PATH%log.txt"
Set TEMP_FILE_PATH="%THIS_DIR_PATH%temp.txt"

Set YYYYMMDD=%date:/=%
Set LEADING_ZERO_TIME=%time: =0%
Set HHMMSS=%LEADING_ZERO_TIME:~0,2%%LEADING_ZERO_TIME:~3,2%%LEADING_ZERO_TIME:~6,2%

Set TEXT_EDITOR=notepad

Echo [%YYYYMMDD% %HHMMSS%] READ %1 >> %LOG_FILE_PATH%
Copy %1 %TEMP_FILE_PATH%
%TEXT_EDITOR% %1